FROM mysql


# docker container run -d --name mysqldb -e MYSQL_ROOT_PASSWORD=rootroot -e MYSQL_DATABASE=employees -e MYSQL_USER=laxman -e MYSQL_PASSWORD=rootroot mysql:8
# docker container exec -it mysqldb mysql --password=rootroot

# mysql> use employees;

# mysql>  CREATE TABLE Persons (
#             PersonID int,
#             LastName varchar(255),
#             FirstName varchar(255),
#             Address varchar(255),
#             City varchar(255)
#          );

#  mysql> Insert into Persons Values (1,'test','test','test','test');

#  mysql> Select * from Persons;

# without creating volumes these are created



